import {chromium} from 'playwright';
import {startServer} from '../src/server.mjs';
import {createModels} from '../src/models.mjs';
import {mkdtemp,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=path.resolve(import.meta.dirname,'..');await mkdir(path.join(root,'test-results'),{recursive:true});
const run=await mkdtemp(path.join(root,'test-results','credentials-ui-'));
const slots=new Map();let failSave=false,saveGate,saveEntered;
const store={capabilities:async()=>({available:true,reason:'<img src=x onerror=alert(1)> synthetic text'}),load:async k=>slots.get(k)||null,save:async(k,v)=>{saveEntered?.();if(saveGate)await saveGate;if(failSave)return {saved:false};slots.set(k,v);return {saved:true};},delete:async k=>{slots.delete(k);return {deleted:true};}};
const providerFixtureCalls=[];
const models=createModels({dataDir:path.join(run,'data'),secretStore:store,fetchImpl:async(url,options)=>{providerFixtureCalls.push({url,model:JSON.parse(options.body).model});return new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:'OK'}}]}));}});
const server=await startServer({dataDir:path.join(run,'data'),models});
let browser;
try{
 browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1280,height:1100}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(server.url+'/#settings');await page.locator('#settings-form').waitFor();
 await page.locator('#provider').selectOption('openai');assert.equal(await page.locator('#settings-form img').count(),0);assert.match(await page.locator('#settings-form').innerText(),/<img src=x/);
 await page.locator('#provider').selectOption('openai');await page.locator('#model').fill('synthetic-no-call');await page.locator('#apiKey').fill('SYNTHETIC-UI');assert.equal(await page.locator('#credentialMode').inputValue(),'encrypted');
 await page.locator('#settings-form button[type=submit]').click();await page.locator('#settings-result .success').waitFor();assert.equal(slots.size,1);
 await page.screenshot({path:path.join(run,'encrypted-settings.png'),fullPage:true});
 let releaseSave;saveGate=new Promise(resolve=>{releaseSave=resolve;});const entered=new Promise(resolve=>{saveEntered=resolve;});
 await page.locator('#model').fill('synthetic-first-model');await page.locator('#apiKey').fill('SYNTHETIC-FIRST');
 await page.locator('#settings-form button[type=submit]').click();await entered;
 await page.locator('#model').fill('synthetic-newer-unsaved-model');await page.locator('#apiKey').fill('SYNTHETIC-NEWER-UNSAVED');
 releaseSave();saveGate=undefined;saveEntered=undefined;
 await page.waitForFunction(()=>!document.querySelector('#settings-form button[type=submit]').disabled);
 assert.equal(await page.locator('#model').inputValue(),'synthetic-newer-unsaved-model');assert.equal(await page.locator('#apiKey').inputValue(),'SYNTHETIC-NEWER-UNSAVED');
 assert.deepEqual([...slots.values()],['SYNTHETIC-FIRST']);assert.match(await page.locator('#settings-result').innerText(),/尚未保存/);
 await page.locator('#settings-form button[type=submit]').click();await page.waitForFunction(()=>document.querySelector('#apiKey').value==='');assert.deepEqual([...slots.values()],['SYNTHETIC-NEWER-UNSAVED']);
 failSave=true;await page.locator('#apiKey').fill('SYNTHETIC-UNSAVED');await page.locator('#settings-form button[type=submit]').click();await page.locator('#settings-result .error').waitFor();assert.match(await page.locator('#settings-result').innerText(),/加密保存失败/);
 await page.locator('#credentialMode').selectOption('session');await page.locator('#settings-form button[type=submit]').click();await page.locator('#settings-result .success').waitFor();assert.equal(slots.size,0);
 await page.locator('#clearApiKey').check();await page.locator('#settings-form button[type=submit]').click();await page.locator('#settings-result .success').waitFor();
 saveGate=new Promise(resolve=>{releaseSave=resolve;});const endpointEntered=new Promise(resolve=>{saveEntered=resolve;});failSave=false;
 await page.locator('[name=consent]').check();
 await page.locator('#provider').selectOption('compatible');await page.locator('#baseUrl').fill('https://synthetic-b.example/v1');await page.locator('#model').fill('synthetic-b-saved');await page.locator('#apiKey').fill('SYNTHETIC-B');await page.locator('#credentialMode').selectOption('encrypted');
 await page.locator('#settings-form button[type=submit]').click();await endpointEntered;
 assert.equal(await page.locator('#test-connection').isDisabled(),true);assert.equal(await page.locator('[name=consent]').isDisabled(),true);
 await page.locator('#model').fill('synthetic-b-newer-unsaved');
 releaseSave();saveGate=undefined;saveEntered=undefined;
 await page.waitForFunction(()=>!document.querySelector('#settings-form button[type=submit]').disabled);
 assert.match(await page.locator('.consent').innerText(),/https:\/\/synthetic-b.example\/v1/);
 assert.equal(await page.locator('[name=consent]').isChecked(),false);
 assert.equal(await page.locator('#model').inputValue(),'synthetic-b-newer-unsaved');
 assert.match(await page.locator('#saved-test-target').innerText(),/synthetic-b-saved/);
 assert.match(await page.locator('#saved-credential-status').innerText(),/已使用本机系统加密保存/);
 await page.locator('#test-connection').click();assert.deepEqual(providerFixtureCalls,[]);
 await page.locator('[name=consent]').check();await page.locator('#test-connection').click();await page.waitForFunction(()=>!document.querySelector('#test-connection').disabled);
 assert.deepEqual(providerFixtureCalls,[{url:'https://synthetic-b.example/v1/chat/completions',model:'synthetic-b-saved'}]);
 await page.screenshot({path:path.join(run,'saved-connection-with-newer-edit.png'),fullPage:true});
 await page.locator('#clearApiKey').check();await page.locator('#settings-form button[type=submit]').click();await page.locator('#settings-result .success').waitFor();
 const state=await page.evaluate(async()=> (await fetch('/api/state')).json());assert.equal(state.settings.hasApiKey,false);assert.deepEqual(errors,[]);
 await writeFile(path.join(run,'evidence.json'),JSON.stringify({checks:['bootstrapped UI save','encrypted option','escaped capability text','delayed save preserves newer model and key edits','newer edits remain unsaved until next explicit Save','save failure visible','session-only removes disk slot','clear removes memory','delayed endpoint save refreshes consent and saved model facts while preserving newer input','old consent cleared; explicit new consent tests only the displayed saved target'],pageErrors:errors,providerFixtureCalls,realProviderCalls:0},null,2));console.log('PASS credential settings and saved transport consent flow');console.log('RESULT_DIR '+run);
}finally{await browser?.close();await server.close();}
