import {saveAndProcessLocal} from './material-ui-helpers.mjs';
import {_electron as electron} from 'playwright';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import assert from 'node:assert/strict';
const root=process.cwd(),packaged=process.argv.includes('--packaged'),run=resolve(root,'test-results',`desktop-${packaged?'portable':'source'}-${Date.now()}`),dataDir=resolve(run,'data');await mkdir(run,{recursive:true});
const executableArg=process.argv.indexOf('--executable');
const executablePath=executableArg>=0?resolve(process.argv[executableArg+1]):packaged?resolve('dist/PracticeBridge-win32-x64/PracticeBridge.exe'):resolve('node_modules/electron/dist/electron.exe');
const env={...process.env,PRACTICEBRIDGE_DATA_DIR:dataDir,PRACTICEBRIDGE_TEST_HIDDEN:'1'};delete env.ELECTRON_RUN_AS_NODE;
let app;const checks=[],errors=[];const pass=x=>{checks.push(x);console.log('PASS '+x);};
async function launch(){const e=await electron.launch({executablePath,args:[...(packaged?[]:[root]),'--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream','--autoplay-policy=no-user-gesture-required'],env,timeout:30000});const p=await e.firstWindow();p.on('pageerror',er=>errors.push(er.message));await p.locator('.hero').waitFor();return {e,p};}
async function screenshot(e,name){const data=await e.evaluate(async({BrowserWindow})=>{const window=BrowserWindow.getAllWindows()[0],visible=window.isVisible();window.showInactive();await new Promise(r=>setTimeout(r,400));const png=(await window.webContents.capturePage()).toPNG().toString('base64');if(!visible)window.hide();return png;});await writeFile(resolve(run,name),Buffer.from(data,'base64'));}
async function closeWindow(e){const closed=e.waitForEvent('close',{timeout:15000});await e.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].close());await closed;}
function pdf(lines){const esc=s=>s.replaceAll('\\','\\\\').replaceAll('(','\\(').replaceAll(')','\\)');const stream=`BT /F1 10 Tf 50 760 Td 16 TL ${lines.map((s,i)=>`${i?'T* ':''}(${esc(s)}) Tj`).join('\n')} ET`;const obs=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`];let s='%PDF-1.4\n',offs=[];obs.forEach((o,i)=>{offs.push(Buffer.byteLength(s));s+=`${i+1} 0 obj\n${o}\nendobj\n`;});const x=Buffer.byteLength(s);s+=`xref\n0 6\n0000000000 65535 f \n${offs.map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')}trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${x}\n%%EOF\n`;return Buffer.from(s);}
try{
  let {e,p}=await launch();app=e;assert.equal(await e.evaluate(({app})=>app.isPackaged),packaged);await screenshot(e,'01-desktop-empty.png');const preferences=await e.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];return w.webContents.getLastWebPreferences();});assert.equal(preferences.nodeIntegration,false);assert.equal(preferences.contextIsolation,true);assert.equal(preferences.sandbox,true);pass('actual Electron window starts empty with renderer isolation');
  const base=new URL(p.url()).origin;await p.goto(base+'/#import');await p.locator('#import-files').setInputFiles(resolve(root,'public/examples/getting-started.zip'));await saveAndProcessLocal(p);await p.locator('#acknowledge').check();await p.locator('#commit-import').click();await p.getByRole('heading',{name:'材料已就位。',exact:true}).waitFor();const s=await p.evaluate(async()=>fetch('/api/state').then(r=>r.json())),lib=s.libraries[0],writing=lib.groups.find(g=>g.section==='writing');await p.goto(`${base}/#practice/${lib.libraryId}/${writing.id}/practice`);await p.locator('[data-token=C]').click();await p.locator('[data-token=B]').click();await p.locator('[data-token=A]').click();await p.locator('#submit-answer').click();await p.locator('#next-question').click();await p.locator('#answer-input').fill('Hi Maya, this is an original desktop persistence fixture.');await closeWindow(e);app=null;
  const disk=JSON.parse(await readFile(resolve(dataDir,'state.json'),'utf8'));assert.ok(disk.sessions.some(session=>Object.values(session.answers).some(a=>a.answer==='Hi Maya, this is an original desktop persistence fixture.')));pass('window close flushes a just-edited writing draft before server shutdown');
  ({e,p}=await launch());app=e;const base2=new URL(p.url()).origin;const snapshot=await p.evaluate(async()=>fetch('/api/state').then(r=>r.json()));const resumed=snapshot.sessions.find(session=>session.groupId===writing.id);await p.goto(`${base2}/#practice/${lib.libraryId}/${writing.id}/practice/${resumed.id}`);await p.locator('#answer-input').waitFor();assert.equal(await p.locator('#answer-input').inputValue(),'Hi Maya, this is an original desktop persistence fixture.');pass('desktop restart resumes the exact saved writing draft');
  const speaking=lib.groups.find(g=>g.questions.some(q=>q.type==='interview'));await p.goto(`${base2}/#practice/${lib.libraryId}/${speaking.id}/practice`);await p.locator('#record-toggle').click();await p.locator('#recorder.recording').waitFor();await e.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].close());await p.waitForTimeout(300);assert.equal(await e.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().length),1);assert.equal(await p.evaluate(async()=>fetch('/api/state').then(r=>r.status)),200);pass('active recording refuses window close without prematurely stopping the local service');await p.locator('#record-toggle').click();await p.locator('#record-status').getByText('录音已保存。',{exact:false}).waitFor();
  const pdfPath=resolve(run,'original.pdf');await writeFile(pdfPath,pdf(['Title: Original PDF fixture','Rights: Original fixture','Reading: Opening time','Passage:','The garden opens at nine.','Questions:','1. When does the garden open?','A. At eight.','B. At nine.','Answer key: 1 B']));await p.goto(base2+'/#import');await p.locator('#import-files').setInputFiles(pdfPath);await saveAndProcessLocal(p);await p.locator('#author-view').waitFor();assert.equal(await p.locator('#commit-import').isDisabled(),false);await screenshot(e,'02-pdf-import.png');pass('PDF extraction and ordinary worksheet parsing run inside the Electron runtime');
  await closeWindow(e);app=null;assert.deepEqual(errors,[]);await writeFile(resolve(run,'result.json'),JSON.stringify({ok:true,packaged,checks,errors,microphone:'synthetic browser capture only'},null,2));console.log('RESULT_DIR '+run);
}catch(error){await writeFile(resolve(run,'failure.txt'),error.stack);console.error(error);console.log('RESULT_DIR '+run);process.exitCode=1;}finally{await app?.close().catch(()=>{});}
