import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {createStore} from '../src/store.mjs';
import {createMaterialInbox} from '../src/materials.mjs';
import {buildExamPlan} from '../src/exam-plan.mjs';
import {resolveTiming} from '../public/exam-timing.mjs';
import {createPackageZip,parseNativeImport,validatePackage,contentHash} from '../src/package.mjs';
import {createExamSession,restoreExamSession} from '../src/exam-session.mjs';
import Ajv2020 from 'ajv/dist/2020.js';
const canonicalV2=new Ajv2020({strict:true,allowUnionTypes:true,allErrors:true,useDefaults:false,coerceTypes:false,removeAdditional:false}).compile(JSON.parse(await fs.readFile(new URL('../docs/practicebridge.v2.schema.json',import.meta.url),'utf8')));
const candidates = await import('../src/material-candidates.mjs').catch(() => ({}));
const compiler = await import('../src/material-compiler.mjs').catch(() => ({}));

test('persist mixed candidates, compile available subset atomically, retry after restart', async t => {
  assert.equal(typeof candidates.createCandidateRepository,'function','persisted candidate repository is required');
  assert.equal(typeof compiler.createMaterialCompiler,'function');
  const dir=await fs.mkdtemp(path.join(os.tmpdir(),'pb-candidates-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));
  let store=await createStore({dataDir:dir}),inbox=createMaterialInbox({store}),repository=candidates.createCandidateRepository({store});
  const material=await inbox.receive({title:'Mixed self-authored',text:'A complete blue flag passage. Broken audio remains original.',files:[{name:'broken.wav',data:Buffer.from('bad attachment').toString('base64')}]});
  const q=(id,answer)=>({id,type:'single_choice',prompt:'What color is the flag?',options:[{id:'A',text:'Blue'},{id:'B',text:'Red'}],answer});
  const pack={schemaVersion:1,id:'mixed',version:'1',title:'Mixed',groups:[{id:'read',title:'Read',section:'reading',taskKind:'read_daily',passage:'A complete blue flag passage.\nAn unreferenced paragraph must survive.',questions:[q('ready','A'),q('unknown',null)]},{id:'listen',title:'Listen',section:'listening',taskKind:'listen_conversation',questions:[q('missing','A')]}]};
  const saved=await repository.ingestPack({materialId:material.id,pack,files:new Map(),method:'native-json',expectedEpoch:store.read().workspaceEpoch});
  assert.equal(saved.candidates.length,3);
  const selected=saved.candidates.filter(c=>c.readiness.canAnswer);
  assert.equal(selected.length,2);
  const request={materialId:material.id,sourceRevision:saved.sourceRevision,candidateRevisions:Object.fromEntries(selected.map(c=>[c.candidateId,c.revision])),selectedIds:selected.map(c=>c.candidateId),importOperationId:'test-operation-1',expectedEpoch:store.read().workspaceEpoch};
  let compile=compiler.createMaterialCompiler({store,repository}).compilePracticeSubset;
  const first=await compile(request);
  assert.equal(canonicalV2(first.normalizedPack),true,JSON.stringify(canonicalV2.errors));
  assert.equal(first.completeness.pending,1);
  assert.match(first.normalizedPack.groups[0].passage,/unreferenced paragraph/);
  assert.equal(first.normalizedPack.groups[0].questions[1].answer,null);
  await store.close();store=await createStore({dataDir:dir});repository=candidates.createCandidateRepository({store});compile=compiler.createMaterialCompiler({store,repository}).compilePracticeSubset;
  assert.deepEqual((await compile(request)).receipt,first.receipt);
  assert.equal(store.read().libraries.length,1);
  await compile({...request,importOperationId:'overlapping-click',selectedIds:[selected[0].candidateId],candidateRevisions:{[selected[0].candidateId]:1}});
  assert.equal(store.read().libraries.length,1,'overlapping selections cannot duplicate an already committed candidate revision');
  assert.equal((await compile({...request,importOperationId:'new-click'})).receipt.libraryId,first.receipt.libraryId);
  assert.equal(store.read().libraries.length,1);
  await assert.rejects(compile({...request,selectedIds:[selected[0].candidateId]}),/冲突|不同/);
  await assert.rejects(compile({...request,importOperationId:'epoch-missing',expectedEpoch:undefined}),/epoch|工作区/i);
  const revision=await repository.patchCandidate({materialId:material.id,candidateId:selected[0].candidateId,expectedRevision:1,expectedEpoch:store.read().workspaceEpoch,fields:{prompt:'Human edited prompt.'},actor:'user'});
  assert.equal(revision.revision,2);
  await assert.rejects(repository.patchCandidate({materialId:material.id,candidateId:selected[0].candidateId,expectedRevision:1,expectedEpoch:store.read().workspaceEpoch,fields:{prompt:'Late model prompt.'},actor:'model'}),/冲突|更新/);
  assert.equal(store.read().libraries[0].originalPack.groups[0].questions[0].prompt,'What color is the flag?');
  const latest=await repository.load(material.id),copy=structuredClone(latest.candidates[0]);copy.untrustedFlag=true;
  assert.throws(()=>candidates.validateCandidate(copy),/结构无效/);
  copy.untrustedFlag=undefined;delete copy.untrustedFlag;copy.revision='2';assert.throws(()=>candidates.validateCandidate(copy),/结构无效/);assert.equal(copy.revision,'2','validator does not coerce input');
  assert.equal(Object.hasOwn(store.read().importReceipts['test-operation-1'],'result'),false,'receipts contain small references, not copies of whole packs');
});

test('original repeat ordinals survive independent export/import and unknown position never uses subset index', async t=>{
  const dir=await fs.mkdtemp(path.join(os.tmpdir(),'pb-ordinal-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));
  const store=await createStore({dataDir:dir}),inbox=createMaterialInbox({store}),repository=candidates.createCandidateRepository({store});
  const material=await inbox.receive({title:'Self-authored repeat',text:'Self-authored six sentence exercise.'});
  const wav=Buffer.alloc(46);wav.write('RIFF');wav.writeUInt32LE(38,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(8000,24);wav.writeUInt32LE(16000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(2,40);
  const pack={schemaVersion:1,id:'repeat',version:'1',title:'Repeat',groups:[{id:'repeat',section:'speaking',taskKind:'listen_repeat',title:'Repeat',questions:Array.from({length:6},(_,i)=>({id:`q${i+1}`,type:'listen_repeat',prompt:'Listen and repeat.',audio:'stimulus.wav',answer:'An original sentence.'}))}]};
  pack.examContractVersion=1;pack.minReaderVersion='0.3.0';pack.examSets=[{id:'set',title:'Original repeat set',sections:[{id:'speaking',section:'speaking',title:'Speaking',modules:[{id:'module',title:'Original module',sourceNumber:2,taskIds:['repeat'],instructions:{text:'Repeat each sentence.',audio:'stimulus.wav',basis:'user',source:'Self-authored source',verifiedContent:false},navigation:{back:'none',review:'none',lockOnAdvance:true}}]}]}];
  const saved=await repository.ingestPack({materialId:material.id,pack,files:new Map([['stimulus.wav',wav]]),method:'native-json',expectedEpoch:store.read().workspaceEpoch});
  const selected=[saved.candidates[2],saved.candidates[5]],request={materialId:material.id,sourceRevision:saved.sourceRevision,selectedIds:selected.map(c=>c.candidateId),candidateRevisions:Object.fromEntries(selected.map(c=>[c.candidateId,1])),importOperationId:'repeat-test',expectedEpoch:store.read().workspaceEpoch};
  const result=await compiler.createMaterialCompiler({store,repository}).compilePracticeSubset(request);
  const exported=await createPackageZip(result.normalizedPack,new Map([['stimulus.wav',wav]]));
  const imported=await parseNativeImport([{name:'subset.zip',data:exported.toString('base64')}]);
  assert.equal(canonicalV2(imported.pack),true,JSON.stringify(canonicalV2.errors));
  assert.deepEqual(imported.pack.examSets[0].sections[0].modules[0].instructions,pack.examSets[0].sections[0].modules[0].instructions);
  assert.equal(imported.pack.examSets[0].sections[0].modules[0].sourceNumber,2);
  const checked=validatePackage(imported.pack,imported.files);assert.deepEqual(checked.issues.filter(i=>i.severity==='error'),[]);
  assert.equal(checked.pack.schemaVersion,2);assert.deepEqual(checked.pack,result.normalizedPack);
  const plan=buildExamPlan(checked.pack),task=plan.sections[0].modules[0].tasks[0];
  assert.deepEqual(task.questionIds.map(id=>resolveTiming(task,{},'document',{questionId:id}).durationSeconds),[10,12]);
  task.sourcePositionsV1[task.questionIds[0]].originalOrdinalInTask=null;
  assert.equal(resolveTiming(task,{},'document',{questionId:task.questionIds[0]}).durationSeconds,12);
  const oldLibrary=store.read().libraries[0];assert.equal(oldLibrary.contentHash,contentHash(oldLibrary.originalPack,oldLibrary.mediaMap));
  const sessionState=store.read(),session=createExamSession({sessionVersion:2,libraryId:oldLibrary.libraryId,mode:'practice'},sessionState);
  assert.deepEqual(session.planSnapshot.sections[0].modules[0].tasks[0].sourcePositionsV1,Object.fromEntries(selected.map(c=>[c.sourceQuestionId,{sourceTaskId:c.sourceTaskId,originalOrdinalInTask:c.originalOrdinalInTask}])));
  assert.doesNotThrow(()=>restoreExamSession(session,sessionState));
  const altered=structuredClone(session);altered.planSnapshot.sections[0].modules[0].tasks[0].sourcePositionsV1[selected[0].sourceQuestionId].originalOrdinalInTask=1;assert.throws(()=>restoreExamSession(altered,sessionState),/原题位置|冻结/);
  const future=structuredClone(checked.pack);future.groups[0].questions[0].futureExecutionField=true;
  assert.ok(validatePackage(future,imported.files).issues.some(i=>i.severity==='error'),'new v2 execution extensions cannot be silently dropped');
});

test('zero-ready and unsupported interactions preserve originals without claiming a library import',async t=>{
  const dir=await fs.mkdtemp(path.join(os.tmpdir(),'pb-pending-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));
  const store=await createStore({dataDir:dir}),inbox=createMaterialInbox({store}),repository=candidates.createCandidateRepository({store});
  const material=await inbox.receive({text:'Self-authored multiple selection source.'});
  const interaction={kind:'multi_select',minimum:2,maximum:3,rows:[{id:'x',text:'Original unhandled row'}]};
  const saved=await repository.ingestPack({materialId:material.id,pack:{schemaVersion:1,id:'pending',title:'Pending',version:'1',groups:[{id:'g',section:'reading',title:'Read',passage:'The full original passage.',questions:[{id:'q',type:'multiple_choice',prompt:'Choose two.',interaction,options:[{id:'A',text:'First'},{id:'B',text:'Second'}],answer:['A','B']}]}]},expectedEpoch:store.read().workspaceEpoch,method:'native-json'});
  assert.equal(saved.candidates[0].readiness.canAnswer,false);const ref=saved.candidates[0].fields.interaction.rawArtifactRef;assert.deepEqual((await repository.readArtifact(ref)).value,interaction);
  const compile=compiler.createMaterialCompiler({store,repository}).compilePracticeSubset;
  const request={materialId:material.id,sourceRevision:saved.sourceRevision,candidateRevisions:{},selectedIds:[],importOperationId:'empty-attempt',expectedEpoch:store.read().workspaceEpoch};
  const result=await compile(request);assert.equal(result.normalizedPack,null);assert.equal(result.receipt,null);assert.equal(result.completeness.pending,1);assert.equal(store.read().libraries.length,0);assert.equal(inbox.get(material.id).text,material.text);
  assert.deepEqual(await compile(request),result);
});
