import {appFetch} from './auth-client.mjs';
import {saveAndProcessLocal} from './material-ui-helpers.mjs';
// Full local UI exercise. All inputs are original fixtures; microphone is a fake
// browser device and the model is a local protocol fixture, never a live account.
import {chromium} from 'playwright';
import {startServer} from '../src/server.mjs';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createServer} from 'node:http';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..'),run=resolve(root,'test-results',`ui-${Date.now()}`),dataDir=resolve(run,'data');
await mkdir(run,{recursive:true});
const checks=[],pageErrors=[];let server,browser,provider;
const pass=x=>{checks.push(x);console.log('PASS '+x);};
const feedback={summary:'回答直接说明了学习地点，可以通过具体情景展开理由。',strengths:['明确回答了学习地点。'],corrections:[{quote:'I study in the library',issue:'可以用一个具体情景展开原因。',suggestion:'补充一次完成作业的例子。',category:'development'}],revisedAnswer:'I study in the library because it is quiet. I can finish my reading without interruptions.',modelAnswer:'I prefer the library because its quiet rooms help me focus. Last week, I finished a long reading assignment there without checking my phone.',nextSteps:['再录一次，并添加一个具体例子。'],limitations:['这是本地协议测试返回值，不是实际模型评价。']};
try{
  provider=createServer(async(req,res)=>{let input='';for await(const c of req)input+=c;const b=JSON.parse(input),name=b.response_format?.json_schema?.name;const answer=name==='practicebridge_feedback'?JSON.stringify(feedback):'这是本地接口联通测试。练习建议：先直接回答问题，再补充一个具体例子。';res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify({choices:[{message:{content:answer},finish_reason:'stop'}]}));});await new Promise(r=>provider.listen(0,'127.0.0.1',r));
  server=await startServer({dataDir});const base=server.url;
  const request=async(path,body,method)=>{const r=await appFetch(`${server.url}/api${path}`,{method:method||(body?'POST':'GET'),headers:{'Content-Type':'application/json','X-PracticeBridge':'1'},...(body?{body:JSON.stringify(body)}:{})});const b=await r.json();assert.equal(r.status,200,JSON.stringify(b));return b;};
  browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream','--autoplay-policy=no-user-gesture-required']});
  const context=await browser.newContext({viewport:{width:1440,height:1024},permissions:['microphone']});
  const page=await context.newPage();page.on('pageerror',e=>pageErrors.push(e.message));
  await page.goto(base);await page.locator('.hero').waitFor();assert.equal((await request('/state')).libraries.length,0);await page.screenshot({path:resolve(run,'01-empty-dashboard.png'),fullPage:true});pass('empty default library and honest zero-state dashboard');
  await page.getByRole('link',{name:'导入我的材料',exact:true}).click();await page.locator('#import-files').setInputFiles(resolve(root,'public/examples/getting-started.zip'));await saveAndProcessLocal(page);await page.locator('#commit-import').waitFor();assert.equal(await page.locator('#author-view').isChecked(),false);assert.equal(await page.locator('#commit-import').isDisabled(),false);await page.screenshot({path:resolve(run,'02-import-review.png'),fullPage:true});await page.locator('#acknowledge').check();await page.locator('#commit-import').click();await page.getByRole('heading',{name:'材料已就位。',exact:true}).waitFor();await page.getByRole('link',{name:'开始练习',exact:false}).last().click();await page.locator('.library-card').first().waitFor();
  let state=await request('/state'),library=state.libraries[0];assert.equal(library.groups.reduce((n,g)=>n+g.questions.length,0),9);await page.screenshot({path:resolve(run,'03-library.png'),fullPage:true});pass('opt-in native import, hidden answers, and nine real fixture questions');
  const reading=library.groups.find(g=>g.section==='reading'),practiceHash=`#practice/${library.libraryId}/${reading.id}/practice`;
  await page.goto(base+'/'+practiceHash);await page.locator('#submit-answer').waitFor();await page.locator('input[name=answer][value=B]').check();await page.locator('#save-exit').click();await page.locator('.library-card').first().waitFor();await page.locator('a[data-nav=dashboard]').click();await page.locator('.hero').waitFor();const resumable=(await request('/state')).sessions.find(s=>s.groupId===reading.id);assert.ok(resumable);await page.goto(`${base}/#practice/${library.libraryId}/${reading.id}/practice/${resumable.id}`);await page.locator('#submit-answer').waitFor();assert.equal(await page.locator('input[name=answer][value=B]').isChecked(),true);pass('draft answer survives exit and session resume');
  await page.locator('#submit-answer').click();await page.locator('#new-attempt').waitFor();await page.locator('#submission-result').getByText('回答正确。',{exact:false}).waitFor();await page.screenshot({path:resolve(run,'04-reading-result.png'),fullPage:true});await page.locator('#new-attempt').click();await page.locator('input[name=answer][value=A]').check();await page.locator('#submit-answer').click();await page.locator('#new-attempt').waitFor();state=await request('/state');assert.equal(state.attempts.length,2);assert.equal(state.attempts[0].answer,'B');assert.equal(state.attempts[1].kind,'retry');assert.equal(state.attempts[1].objective.status,'incorrect');pass('first attempt and retry remain independent with exact objective results');
  await page.locator('#next-question').click();await page.locator('input[name=answer][value=C]').check();await page.locator('#submit-answer').click();await page.locator('#next-question').waitFor();await page.locator('#next-question').click();await page.locator('#answer-input').fill('volunteers');await page.locator('#submit-answer').click();await page.locator('#next-question').waitFor();await page.locator('#next-question').click();await page.getByRole('heading',{name:'这一轮，已经留下进步的起点。'}).waitFor();pass('reading group completion and objective summary');
  const speaking=library.groups.find(g=>g.questions.some(q=>q.type==='interview'));const speakingHash=`#practice/${library.libraryId}/${speaking.id}/practice`;
  await page.goto(base+'/'+speakingHash);await page.locator('#record-toggle').waitFor();assert.equal(await page.locator('#prompt-details').getAttribute('open'),null);await page.locator('#prompt-audio').evaluate(async a=>{await a.play();});await page.waitForFunction(()=>document.querySelector('#prompt-audio')?.duration>0&&document.querySelector('#prompt-audio')?.currentTime>0);await page.locator('#prompt-audio').evaluate(a=>a.pause());pass('prompt audio decodes and plays with transcript initially collapsed');
  await page.locator('#record-toggle').click();await page.locator('#recorder.recording').waitFor();await page.waitForTimeout(1200);await page.locator('#record-toggle').click();await page.locator('#record-status').getByText('录音已保存。',{exact:false}).waitFor();await page.locator('summary').filter({hasText:'文字转写与反馈准备'}).click();await page.locator('#transcript').fill('I study in the library because it is quiet.');await page.locator('#transcript-confirmed').check();await page.locator('#submit-answer').click();await page.locator('#new-attempt').waitFor();state=await request('/state');const originalSpeech=state.attempts.find(a=>a.questionSnapshot.type==='interview');assert.ok(originalSpeech?.recordingId);const audioBytes=Buffer.from(await (await appFetch(base+originalSpeech.recordingUrl)).arrayBuffer());assert.ok(audioBytes.length>100);const originalHash=createHash('sha256').update(audioBytes).digest('hex');await page.screenshot({path:resolve(run,'05-speaking.png'),fullPage:true});pass('fake microphone input traverses MediaRecorder, durable upload, and immutable speaking attempt');
  await page.locator('#new-attempt').click();await page.locator('#record-toggle').click();await page.locator('#recorder.recording').waitFor();await page.waitForTimeout(800);await page.locator('#record-toggle').click();await page.locator('#record-status').getByText('录音已保存。',{exact:false}).waitFor();await page.locator('summary').filter({hasText:'文字转写与反馈准备'}).click();await page.locator('#transcript').fill('I study in the library. I finished a long reading assignment there yesterday.');await page.locator('#transcript-confirmed').check();await page.locator('#submit-answer').click();await page.locator('#new-attempt').waitFor();state=await request('/state');const speechAttempts=state.attempts.filter(a=>a.questionSnapshot.type==='interview');assert.equal(speechAttempts.length,2);assert.notEqual(speechAttempts[0].recordingId,speechAttempts[1].recordingId);assert.equal(speechAttempts[1].kind,'retry');pass('speaking retry has a distinct recording and preserves original transcript');
  await page.locator('a[data-nav=settings]').click();await page.locator('#settings-form').waitFor();await page.locator('#provider').selectOption('compatible');await page.locator('#baseUrl').fill(`http://127.0.0.1:${provider.address().port}/v1`);await page.locator('#model').fill('local-protocol-fixture');await page.locator('#settings-form button[type=submit]').click();await page.locator('#settings-result .success').waitFor();assert.ok((await page.locator('.consent').innerText()).includes(`127.0.0.1:${provider.address().port}`));await page.locator('input[name=consent]').check();await page.locator('#test-connection').click();await page.locator('#settings-result .success').waitFor();pass('settings save refreshes actual recipient and compatible HTTP adapter connection test');
  await page.locator('a[data-nav=analytics]').click();await page.locator('#filter-section').selectOption('speaking');await page.locator('[data-report]').last().click();await page.locator('.modal').waitFor();await page.locator('.modal summary').filter({hasText:'请求本次作答的 AI 反馈'}).click();await page.locator('.modal input[name=consent]').check();await page.locator('#request-feedback').click();let feedbackState;for(let n=0;n<40;n++){feedbackState=await request('/state');if(feedbackState.attempts.find(a=>a.id===originalSpeech.id)?.evaluations.length)break;await new Promise(r=>setTimeout(r,100));}assert.equal(feedbackState.attempts.find(a=>a.id===originalSpeech.id).evaluations.length,1);assert.equal(feedbackState.attempts.find(a=>a.id===speechAttempts[1].id).evaluations.length,0);await page.locator('.modal .close').click();await page.locator('[data-report]').last().click();await page.locator('.modal').getByRole('heading',{name:'反馈与下一步'}).waitFor();await page.screenshot({path:resolve(run,'06-feedback.png'),fullPage:true});pass('real local HTTP model protocol produces source-bound feedback without overwriting retry');await page.locator('.modal .close').click();
  await page.locator('#filter-scope').selectOption('latest');assert.equal(await page.locator('.data-table tbody tr').count(),1);await page.locator('#clear-filters').click();assert.equal(await page.locator('.data-table tbody tr').count(),6);await page.screenshot({path:resolve(run,'07-analytics.png'),fullPage:true});pass('analytics filters and latest-attempt scope reflect actual records');
  const exportResponse=await appFetch(base+`/api/library/${library.libraryId}/export`),exportBytes=Buffer.from(await exportResponse.arrayBuffer());const backupResponse=await appFetch(base+'/api/backup'),backupBytes=Buffer.from(await backupResponse.arrayBuffer());assert.equal(exportResponse.status,200);assert.equal(backupResponse.status,200);await writeFile(resolve(run,'library-export.zip'),exportBytes);await writeFile(resolve(run,'private-backup.zip'),backupBytes);
  await page.locator('a[data-nav=dashboard]').click();await page.locator('.hero').waitFor();await page.setViewportSize({width:900,height:800});await page.screenshot({path:resolve(run,'08-compact.png'),fullPage:true});await page.setViewportSize({width:430,height:930});await page.screenshot({path:resolve(run,'09-mobile.png'),fullPage:true});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false);pass('compact layouts render without horizontal page overflow');
  await context.close();await server.close();server=await startServer({dataDir});state=await request('/state');assert.equal(state.attempts.length,6);assert.equal(state.attempts.find(a=>a.id===originalSpeech.id).evaluations.length,1);const restartedBytes=Buffer.from(await(await appFetch(server.url+originalSpeech.recordingUrl)).arrayBuffer());assert.equal(createHash('sha256').update(restartedBytes).digest('hex'),originalHash);pass('restart preserves attempts, feedback and byte-identical recording');
  const playback=await browser.newPage();await playback.goto(server.url);await playback.locator('.hero').waitFor();await playback.evaluate(url=>{const a=document.createElement('audio');a.id='restarted-audio';a.src=url;document.body.appendChild(a);return a.play();},server.url+originalSpeech.recordingUrl);await playback.waitForFunction(()=>document.querySelector('#restarted-audio')?.currentTime>0);await playback.close();pass('saved recording actually replays after application restart');
  const clean=await startServer({dataDir:resolve(run,'clean')});try{const f=async(path,body)=>{const r=await appFetch(clean.url+'/api'+path,{method:'POST',headers:{'Content-Type':'application/json','X-PracticeBridge':'1'},body:JSON.stringify(body)});const v=await r.json();assert.equal(r.status,200,JSON.stringify(v));return v;};const preview=await f('/import/preview',{files:[{name:'export.zip',data:exportBytes.toString('base64')}]});const committed=await f('/import/commit',{draftId:preview.draftId,pack:preview.pack,acknowledged:true});assert.equal(committed.library.groups.length,library.groups.length);assert.deepEqual(committed.library.groups.map(g=>g.questions.map(q=>[q.id,q.answer])),library.groups.map(g=>g.questions.map(q=>[q.id,q.answer])));await f('/restore',{file:{name:'backup.zip',data:backupBytes.toString('base64')}});const restored=await(await appFetch(clean.url+'/api/state')).json();assert.equal(restored.attempts.length,6);pass('package round trip and verified backup restore in a clean data directory');}finally{await clean.close();}
  assert.deepEqual(pageErrors,[]);pass('no uncaught browser JavaScript errors');
  await writeFile(resolve(run,'result.json'),JSON.stringify({ok:true,checks,limitations:['Microphone capture uses a synthetic browser input, not human speech.','Model responses use a local protocol fixture, not a live model or paid account.','This test does not claim official score calibration.'],pageErrors},null,2));console.log('RESULT_DIR '+run);
}catch(error){await writeFile(resolve(run,'failure.txt'),error.stack);console.error(error);console.log('RESULT_DIR '+run);process.exitCode=1;}finally{await browser?.close();await server?.close();await new Promise(r=>provider?.close(r)||r());}
